"""create psicologas table

Revision ID: 361f4a0ca733
Revises: 
Create Date: 2026-02-04 22:52:10.463865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361f4a0ca733'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psicologas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('crp', sa.String(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crp'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_psicologas_id'), 'psicologas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psicologas_id'), table_name='psicologas')
    op.drop_table('psicologas')
    # ### end Alembic commands ###
